import os
from dotenv import load_dotenv

load_dotenv()
os.getenv(".env")

SERVER_STELARIUM = "http://192.168.100.69:8090/api"
RESOLUCAO_MOTOR = 1.8
TIPO_PASSO = "Full"
REDUCAO = 99.5
RESOLUCAO_ATUADOR = RESOLUCAO_MOTOR / REDUCAO
ROTACAO_TERRA_GRAUS_SEGUNDO = 15 / 3600
DELAY_ATUALIZACAO = 0.1  # RESOLUCAO_ATUADOR/ROTACAO_TERRA_GRAUS_SEGUNDO
STEP_DELAY = 0.001
INIT_STEP_DELAY = 0.05

STEP_PIN_DEC = int(os.environ.get("STEP_PIN_DEC"))
DIR_PIN_DEC = int(os.environ.get("DIR_PIN_DEC"))

STEP_PIN_RA = int(os.environ.get("STEP_PIN_RA"))
DIR_PIN_RA = int(os.environ.get("DIR_PIN_RA"))

PIN_BUTTON_HOME = int(os.environ.get("PIN_BUTTON_HOME"))

LIMIT_SWITCH_DEC = int(os.environ.get("LIMIT_SWITCH_DEC"))
LIMIT_SWITCH_RA = int(os.environ.get("LIMIT_SWITCH_RA"))

OFFSET_DEC = 7
OFFSET_RA = 7

LONGITUDE = -40.3351
LATITUDE = -20.3367
ELEVACAO = 6
